Ultrachess deployment
cartesi/rollups-deployment pull request #11
Opened 2022-10-26 04:30 UTC by TheExpandingPolytope

2022-12-02 12:01 UTC, endersonmaia commented
Hey @TheExpandingPolytope , please use the conventional commit style, with something like feat: add <dapp-name>@<network> DApp

One last ting, take a look at the CI results, you may need do make some adjustments during to the build and deployment.

Thanks

2022-12-02 18:13 UTC, endersonmaia requested changes
Waiting commit message rewrite to approve and merge.

DApp backend deployed and the `/graphql` and `/inspect` paths available at the following urls:

- `https://0x25b69635d09b97c0d00404c5b0ca6144dbcecd49.polygon-mumbai.rollups.staging.cartesi.io`
- `https://ultrachess.polygon-mumbai.rollups.staging.cartesi.io`

2022-12-02 21:16 UTC, TheExpandingPolytope commented
Awesome. Commit message updated "[feat: add ultrachess@polygon_mumbai DApp](https://github.com/cartesi/rollups-deployment/pull/11/commits/6ef5f9162480b276ea83446b9a457747cf2ae93a)"
Thanks.

2022-12-09 20:48 UTC, endersonmaia approved these changes

2022-12-13 13:28 UTC, endersonmaia approved these changes

2022-12-13 13:29 UTC, merged