Feat/adapt rollups values to 1.3
cartesi/rollups-deployment pull request #39
Opened 2024-02-06 06:52 UTC by oap75

2024-02-07 10:41 UTC, endersonmaia requested changes

2024-02-07 10:41 UTC, endersonmaia commented on echo-python/sepolia.values.yaml
> +          readOnly: false
We have definition and mention this at cartesi/cloud-infra, I think it's difficult to have this reference here to a code in another repository.

I don't know how to define the `image` here without defining the whole `initContainer`.

Can we create an arbitrary `.Value` element and reference it elsewhere? Like `validator.application.image`, or maybe we'll need to keep this element at our helm-chart for this case.

rollups-node expects to find a cartesi machine snapshot where you point `CARTESI_SNAPSHOT_DIR`.

We could bring the `extraVolume` and `extraVolume` definition here, to keep full context in one place.

It's not the clean and small yaml we wanted in the beginning, but I see no other solution.

2024-02-07 10:47 UTC, oap75 commented on echo-python/sepolia.values.yaml
> +          readOnly: false
I agree, We should find an alternate way. 
So, I think as U said we can get help from the values. 
Just define the image from values and then use it in init container. But I don't know if it's possible or not. 

If we can do the way successfully, the only thing we need is just to add a single value to set the appropriate image name based on each dapp and chain.

2024-02-07 11:18 UTC, oap75 commented on echo-python/sepolia.values.yaml
> +          readOnly: false
related PR : https://github.com/cartesi/helm-charts/pull/83

2024-02-07 12:37 UTC, oap75 commented on echo-python/sepolia.values.yaml
> +          readOnly: false
> related PR : [cartesi/helm-charts#83](https://github.com/cartesi/helm-charts/pull/83)

This handles the problem. 
I'll fix the current PR when the helm chart PR merged.

2024-02-15 11:07 UTC, endersonmaia requested changes

2024-02-15 11:07 UTC, endersonmaia commented on echo-python/sepolia.values.yaml
> +    AWS_ROLE_SESSION_NAME: echo-python-authority-claimer
There's no `AWS_ROLE_SESSION_NAME` configuration, although it may work, it's confusing.

We should use `validator.extraEnvVars` instead.

2024-02-19 09:17 UTC, merged